### ISSUE TITLE
Need clearer instructions around modifying themes/CSS

### ISSUE THREAD

**Issue by Frijol** [tessel/tesselwww#2]
I don't use gulp much, but haven't figured out how to use it as per the Readme instructions here.

I tried running it as shown in the readme, got:
```sh
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Liftoff.buildEnvironment (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:113:52)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:181:32)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:174:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:148:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:31:11
    at FSReqWrap.oncomplete (fs.js:123:15)
```

ran a `npm i -g gulp` because my gulp is probably really out of date, tried again and got

```sh
[10:46:23] Local gulp not found in ~/tesselwww/themes
[10:46:23] Try running: npm install gulp
```

so I ran `npm i gulp` as suggested, tried again with the `gulp watch` and got

```sh
[10:47:10] No gulpfile found
```

What am I missing?

**Comment by tcr** [comment]
Apparently I can't tell the difference between gulp and grunt :)

Can you re-run the instructions in the README now? `grunt` should work, and I've corrected the path to the themes folder.

**Comment by Frijol** [comment]
Ah, much better.

Well, except the error:

```
➜  tessel git:(master) grunt watch
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token )
Warning: Task "watch" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by tcr** [comment]
@Frijol You're in this folder? https://github.com/tessel/tesselwww/tree/master/themes/tessel

Can you try destroying your `node_modules/` folder and re-running `npm i`? And then make sure the `Gruntfile.js` is the same as in on Github?

**Comment by Frijol** [comment]
all checked, same error.
